# This is a basic workflow to help you get started with Actions

name: Clean workflow
on:
 workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  job_one:
    name: Clean
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            unalias rm
            rm -rf daveluma.github.io
